name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
    - main
    - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Run plugin check
      uses: wordpress/plugin-check-action@v1
      with:
        repo-token: ''
        build-dir: './'
        checks: ''
        exclude-checks: ''
        categories: 'plugin_repo'
        exclude-directories: 'tests/*'
        ignore-warnings: ''
        ignore-errors: ''
        include-experimental: ''
        wp-version: 'latest'
  phpstan:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 'latest'
          coverage: none
          tools: composer, cs2pr
      - name: Install PHP dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: '--prefer-dist --no-scripts'  
      - name: PHPStan
        run: composer phpstan